wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/scripts/upload_jaster.py
    python_version: 3.11.5
    cli_version: 0.16.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701160741.660131
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.11.5
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
