wandb:
  run_name: stabilityai/japanese-stablelm-2-instruct-1_6b
api: vllm
num_gpus: 1
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: stabilityai/japanese-stablelm-2-instruct-1_6b #if you use openai api, put the name of model
  bfcl_model_id: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: stabilityai/japanese-stablelm-2-instruct-1_6b
  size_category: <10B
  size: 1644515328
  release_date: 5/9/2024
  max_model_len: 3200
