wandb:
  run_name: "openai/gpt-4o-2024-11-20" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: openai
batch_size: 32 # vllmは256, apiは32を推奨
# inference_interval: 1 # seconds

model:
  pretrained_model_name_or_path: "gpt-4o-2024-11-20" #if you use openai api, put the name of model
  bfcl_model_id: "gpt-4o-2024-11-20-FC"
  size_category: "api"
  size: null
  release_date: "11/20/2024"

run:
  jaster: false
  jmmlu_robustness: false # if this is set as true, jaster should set as true
  mtbench: false
  jbbq: false
  toxicity: false
  jtruthfulqa: false
  hle: false
  swebench: true
  bfcl: false
  hallulens: false
  arc_agi: false
  m_ifeval: false
  aggregate: false

testmode: false
