wandb:
  run_name: stabilityai/stablelm-2-12b-chat
api: vllm
num_gpus: 2
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: stabilityai/stablelm-2-12b-chat #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: stabilityai/stablelm-2-12b-chat
  size_category: 10B≤ <30B
  size: 12143185920
  release_date: 4/8/2024
