wandb:
  run_name: mistral/mistral-medium-2505
api: mistral
batch_size: 32
model:
  pretrained_model_name_or_path: mistral-medium-2505
  bfcl_model_id: mistral-medium-2505-FC
  base_model: "unknown"
  size_category: api
  size: null
  release_date: 05/25/2024 