wandb:
  run_name: anthropic/claude-3-5-haiku-20241022
api: amazon_bedrock
batch_size: 1
inference_interval: 5
model:
  pretrained_model_name_or_path: anthropic.claude-3-5-haiku-20241022 #if you use openai api, put the name of model
  bfcl_model_id: anthropic.claude-3-5-haiku-20241022 # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  size_category: api
  size: null
  release_date: 10/22/2024
  enable_thinking: false  # Disable thinking mode by default (Claude 3.5 Haiku doesn't support it)
