wandb:
  run_name: CohereForAI/c4ai-command-r-08-2024
api: vllm
num_gpus: 4
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: CohereForAI/c4ai-command-r-08-2024 #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: CohereForAI/c4ai-command-r-08-2024
  size_category: 30B≤
  size: 32296476672
  release_date: 8/30/2024
