wandb:
  run_name: mistralai/Mistral-7B-Instruct-v0.2
api: vllm
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: mistralai/Mistral-7B-Instruct-v0.2 #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: mistralai/Mistral-7B-Instruct-v0.2
  size_category: <10B
  size: 7241732096
  release_date: 12/11/2023
