wandb:
  log: True
  entity: "wandb-japan"
  project: "llm-leaderboard-test"
  run_name: "tokyotech-llm/Swallow-MS-7b-v0.1" # use run_name defined above

github_version: v2.0.0 #for recording

testmode: true

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm

model:
  use_wandb_artifacts: false
  artifacts_path: ""
  pretrained_model_name_or_path: "tokyotech-llm/Swallow-MS-7b-v0.1" #if you use openai api, put the name of model
  dtype: 'float16'
  max_model_len: 4096
  trust_remote_code: true
  device_map: "auto"
  load_in_8bit: false
  load_in_4bit: false

generator:
  top_p: 1.0
  # top_k: 0
  temperature: 0.1
  # repetition_penalty: 1.0
  max_tokens: 128

custom_prompt_template: "以下に、あるタスクを説明する指示があり、それに付随する入力が更なる文脈を提供しています。リクエストを適切に完了するための回答を記述してください。\n\n ### 指示:\n{instruction}\n\n### 入力:\n{input}\n\n### 応答:"

num_few_shots: 4

llm_jp_eval:
  aaa: aaa

mtbench:
  temperature_override:
    roleplay: 0.7
    aaa: 0.7
  question_artifacts_path: 'wandb-japan/llm-leaderboard/mtbench_ja_question:v0' # if testmode is true, small dataset will be used
  referenceanswer_artifacts_path: 'wandb-japan/llm-leaderboard/mtbench_ja_referenceanswer:v0' # if testmode is true, small dataset will be used
  judge_prompt_artifacts_path: 'wandb-japan/llm-leaderboard/mtbench_ja_prompt:v1' 
  bench_name: 'japanese_mt_bench'
  model_id: null # cannot use '<', '>', ':', '"', '/', '\\', '|', '?', '*', '.'
  question_begin: null 
  question_end: null 
  max_new_token: 1024
  num_choices: 1
  num_gpus_per_model: 1
  num_gpus_total: 1
  max_gpu_memory: null
  dtype: bfloat16 # None or float32 or float16 or bfloat16
  # for gen_judgment
  judge_model: 'gpt-4'
  mode: 'single'
  baseline_model: null 
  parallel: 1
  first_n: null

jmmlu:
  aaa: aaa

mmlu:
  aaa: aaa

lctg-bench:
  aaa: aaa

bbq:
  aaa: aaa

sample_dataset:
  artifacts_path: 't-ibi/llm-leaderboard/sample_dataset:v1'
  language: ja
#jbbq:

#ly_toxicity:
