wandb:
  run_name: stabilityai/StableBeluga-7B
api: vllm
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: stabilityai/StableBeluga-7B #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: stabilityai/StableBeluga-7B
  size_category: <10B
  size: 6738415616
  release_date: 7/27/2023
