wandb:
  run_name: meta-llama/Llama-3.2-1B-Instruct
api: vllm
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: meta-llama/Llama-3.2-1B-Instruct #if you use openai api, put the name of model
  bfcl_model_name: "meta-llama/Llama-3.2-1B-Instruct-FC" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: meta-llama/Llama-3.2-1B-Instruct
  size_category: <10B
  size: 1235814400
  release_date: 9/25/2024
  max_model_len: 64000
