wandb:
  run_name: tokyotech-llm/Swallow-13b-instruct-v0.1
api: vllm
num_gpus: 2
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: tokyotech-llm/Swallow-13b-instruct-v0.1 #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: tokyotech-llm/Swallow-13b-instruct-v0.1
  size_category: 10B≤ <30B
  size: 13130306560
  release_date: 4/26/2024
