wandb:
  run_name: openai/o1-2024-12-17
api: openai_responses # openai, anthropic, google,.. 
batch_size: 32
model:
  pretrained_model_name_or_path: o1-2024-12-17 # if you use openai api, put the name of model
  bfcl_model_id: "OpenAIResponsesHandler-FC" # find id from "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  base_model: "unknown"
  size_category: api
  size: null
  release_date: 12/17/2024 # format: MM/DD/YYYY

generator:
  reasoning:
    effort: "high"
    summary: "auto"
  temparature: None

