# 新しいOSSモデル追加のためのサンプル設定ファイル
# このファイルは、統合OSSハンドラーを使用して新しいモデルを簡単に追加する方法を示しています
#
# 使用方法:
# 1. このファイルをコピーして新しいモデル名に変更
# 2. model.pretrained_model_name_or_pathとchat_templateを設定
# 3. model.bfcl_model_idを"oss_handler"に設定（重要！）
# 4. サイズカテゴリとその他の情報を入力
# 5. chat_templates/ディレクトリに対応するjinjaファイルを作成
#
# 統合OSSハンドラーが自動的に以下を処理します:
# - 出力パターンの自動検出とデコード
# - モデル固有の前処理
# - chat templateからの設定取得
# - 生の出力の保存（デバッグ用）

wandb:
  run_name: example-org/example-model-7b-instruct  # 評価結果に表示される名前
api: vllm
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: example-org/example-model-7b-instruct  # Hugging Face Hub上のモデル名
  bfcl_model_id: "oss_handler"  # ★重要★ 統合OSSハンドラーを使用
  chat_template: example-org/example-model-7b-instruct  # chat_templates/ディレクトリ内のjinjaファイル名
  size_category: <10B  # サイズカテゴリ: <10B, 10B≤ <30B, 30B≤, api
  size: 7000000000  # パラメータ数（概算値）
  release_date: 1/1/2024  # モデルのリリース日 (MM/DD/YYYY)
  max_model_len: 4096  # 最大入力長（必要に応じて調整）

# BFCLの設定（必要に応じてカスタマイズ）
bfcl:
  artifacts_path: "llm-leaderboard/bfcl-requests:latest"  # BFCLデータセットのartifactパス
  test_category: "all"  # テストカテゴリ（"all"または特定カテゴリのリスト）
  samples_per_category: 20  # 各カテゴリから取得するサンプル数 