wandb:
  run_name: mistral/mistral-large
api: mistral
batch_size: 1
model:
  pretrained_model_name_or_path: mistral-large #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  size_category: api
  size: null
  release_date: 2/26/2024
