wandb:
  run_name: "microsoft/Phi-4-mini-instruct" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  max_model_len: 3500 # update 
  pretrained_model_name_or_path: "microsoft/Phi-4-mini-instruct" #if you use openai api, put the name of model
  chat_template: "microsoft/Phi-4-mini-instruct"
  size_category: "<10B"
  size: 384000000000
  release_date: "6/11/2025"