wandb:
  run_name: anthropic/claude-3-7-sonnet-20250219-v1:0
api: amazon_bedrock
batch_size: 32
model:
  pretrained_model_name_or_path: us.anthropic.claude-3-7-sonnet-20250219-v1:0 #if you use openai api, put the name of model
  bfcl_model_id: "claude-3-7-sonnet-20250219-FC" # find id from "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  base_model: "unknown"
  size_category: api
  size: null
  release_date: 2/19/2025

