wandb:
  run_name: stockmark/stockmark-100b-instruct-v0.1
api: vllm
num_gpus: 4
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: stockmark/stockmark-100b-instruct-v0.1 #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: stockmark/stockmark-100b-instruct-v0.1
  size_category: 30B≤
  size: 98251629568
  release_date: 5/16/2024
