wandb:
  run_name: openai/gpt-4-0613
api: openai
batch_size: 32
model:
  pretrained_model_name_or_path: gpt-4-0613 #if you use openai api, put the name of model
  bfcl_model_id: "OpenAI-FC" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  size_category: api
  size: null
  release_date: 6/13/2023
