wandb:
  run_name: google/gemini-2.5-pro
api: google # openai, anthropic, google,..
batch_size: 32
model:
  pretrained_model_name_or_path: gemini-2.5-pro #if you use openai api, put the name of model
  bfcl_model_id: "gemini-2.5-pro-FC" # find id from "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  base_model: "unknown"
  size_category: api
  size: null
  release_date: 6/17/2025
