wandb:
  run_name: Qwen/Qwen2-72B-Instruct
api: vllm
num_gpus: 2
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: Qwen/Qwen2-72B-Instruct #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: Qwen/Qwen2-72B-Instruct
  size_category: 30B≤
  size: 72706203648
  release_date: 3/28/2024
