wandb:
  run_name: "google/gemini-1.5-flash" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthropic", "google", "cohere", "vllm", "mistral", "bedrock"
api: google
batch_size: 1 # vllmは256, apiは32を推奨
testmode: true

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "gemini-1.5-flash" #if you use openai api, put the name of model
  chat_template: null
  size: "api"
  release_date: "2/9/2024"