wandb:
  run_name: openai/gpt-4-1-mini-2025-04-14
api: openai_responses # openai, anthropic, google,.. 
batch_size: 32
model:
  pretrained_model_name_or_path: gpt-4.1-mini-2025-04-14 # if you use openai api, put the name of model
  bfcl_model_id: "gpt-4.1-mini-2025-04-14-FC" # find id from "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  base_model: "unknown"
  size_category: api
  size: null
  release_date: 4/14/2025 # format: MM/DD/YYYY

