wandb:
  run_name: us.amazon.nova-lite-v1:0
api: amazon_bedrock
batch_size: 8
inference_interval: 2
model:
  pretrained_model_name_or_path: us.amazon.nova-lite-v1:0
  bfcl_model_id: "nova-lite-v1.0"
  size_category: api
  size: null
  release_date: 12/3/2024
