wandb:
  run_name: cohere/command-r-plus-v1:0
api: amazon_bedrock
batch_size: 1
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: cohere.command-r-plus-v1:0 #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  size_category: api
  size: null
  release_date: 4/4/2024
