wandb:
  run_name: openai/o4-mini-2025-04-16
api: openai_responses # openai, anthropic, google,.. 
batch_size: 32
model:
  pretrained_model_name_or_path: o4-mini-2025-04-16 # if you use openai api, put the name of model
  bfcl_model_id: "OpenAIResponsesHandler-FC" # not listed in SUPPORTED_MODELS.md; using Generic OpenAI Handler
  base_model: "unknown"
  size_category: api
  size: null
  release_date: 4/16/2025 # format: MM/DD/YYYY

generator:
  reasoning:
    effort: "high"
    summary: "auto"
  temparature: None

