wandb:
  run_name: elyza/Llama-3-ELYZA-JP-8B
api: vllm
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: elyza/Llama-3-ELYZA-JP-8B #if you use openai api, put the name of model
  bfcl_model_id: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: meta-llama/Meta-Llama-3-8B-Instruct
  size_category: <10B
  size: 8030261248
  release_date: 6/26/2024
  max_model_len: 4096
