wandb:
  run_name: openai/gpt-4o-2024-11-20
api: openai_responses # openai, anthropic, google,..
batch_size: 32
model:
  pretrained_model_name_or_path: gpt-4o-2024-11-20 #if you use openai api, put the name of model
  bfcl_model_id: "gpt-4o-2024-11-20-FC" # find id from "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  base_model: "unknown"
  size_category: api
  size: null
  release_date: 11/20/2024 # format: MM/DD/YYYY

swebench:
  background_eval: true
  api_server:
    enabled: true
    endpoint: 'https://api.nejumi-swebench.org'
