wandb:
  run_name: MiniMaxAI/MiniMax-M2
api: vllm-docker
num_gpus: 8
batch_size: 128
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: MiniMaxAI/MiniMax-M2
  bfcl_model_id: "unified-oss-fc"
  size_category: "Large (30B+)"
  size: 228703644928
  release_date: 10/27/2025

vllm: # This config not used because vLLM launched manually, but for record
  vllm_tag: v0.12.0
  lifecycle: always_on
  gpu_memory_utilization: 0.95
  reasoning_parser: minimax_m2
  tool_call_parser: minimax_m2
  enable_auto_tool_choice: true
  trust_remote_code: true
  extra_args:
    - "--enable-expert-parallel"

generator:
  max_tokens: 196608
  temperature: 1.0
  top_p: 0.95

jaster:
  override_max_tokens: 196608

jbbq:
  generator_config:
    max_tokens: 196608
    temperature: 1.0
    top_p: 0.95

toxicity:
  generator_config:
    max_tokens: 196608
    temperature: 1.0
    top_p: 0.95

jtruthfulqa:
  generator_config:
    max_tokens: 196608
    temperature: 1.0
    top_p: 0.95

swebench:
  max_tokens: 196608

mtbench:
  generator_config:
    max_tokens: 196608
    temperature: 1.0
    top_p: 0.95
  temperature_override:
    writing: 0.6
    roleplay: 0.6
    extraction: 0.6
    math: 0.6
    coding: 0.6
    reasoning: 0.6
    stem: 0.6
    humanities: 0.6

bfcl:
  generator_config:
    max_tokens: 196608
    temperature: 1.0
    top_p: 0.95

hallulens:
  generator_config:
    max_tokens: 196608
    temperature: 1.0
    top_p: 0.95

hle:
  generator_config:
    max_tokens: 196608
    temperature: 1.0
    top_p: 0.95

arc_agi:
  max_output_tokens: 196608
