wandb:
  run_name: tokyotech-llm/Swallow-MS-7b-v0.1
api: vllm
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: tokyotech-llm/Swallow-MS-7b-v0.1 #if you use openai api, put the name of model
  bfcl_model_id: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: tokyotech-llm/Swallow-MS-7b-instruct-v0.1
  size_category: <10B
  size: 7330205696
  release_date: 3/11/2024
