wandb:
  run_name: "openai/gpt-5.4-2026-03-05: xhigh-effort"
api: openai_responses # openai, anthropic, google,..
batch_size: 8
model:
  pretrained_model_name_or_path: gpt-5.4-2026-03-05 # if you use openai api, put the name of model
  bfcl_model_id: "gpt-5.4-2026-03-05-FC"
  base_model: "unknown"
  size_category: api
  size: null
  release_date: 3/5/2026 # inferred from the dated model id in OpenAI's official docs


generator: # LLM client default configuration: to be overridden by each benchmark
  parallel_tool_calls: true
  max_tokens: 128000
  text:
    verbosity: medium
  extra_body:
    reasoning:
      effort: xhigh

jaster:
  override_max_tokens: 128000 # if null, use value defined in task dataset files

jbbq:
  generator_config:
    max_tokens: 128000

toxicity:
  generator_config:
    max_tokens: 128000

jtruthfulqa:
  generator_config:
    max_tokens: 128000

swebench:
  max_tokens: 128000
  fc_enabled: true

mtbench:
  generator_config:
    max_tokens: 128000

bfcl:
  generator_config:
    max_tokens: 128000
    include:
      - reasoning.encrypted_content

hallulens:
  generator_config:
    max_tokens: 128000

hle:
  generator_config:
    max_tokens: 128000

arc_agi:
  max_output_tokens: 128000

m_ifeval:
  generator_config:
    max_tokens: 128000

openai:
  http_timeout:
    connect: 10.0
    read: 1800.0
    write: 300.0
    pool: 30.0
