wandb:
  run_name: "microsoft/phi-4"

api: "openai-compatible"
base_url: "https://openrouter.ai/api/v1"  # 外部APIのエンドポイント
batch_size: 32

model:
  pretrained_model_name_or_path: "microsoft/phi-4"  # APIで使用するモデル名
  bfcl_model_id: "microsoft/phi-4"  # find id from "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  size_category: "Medium (10–30B)" # "Small (<10B)", "Medium (10–30B)", "Large (30B+)"
  size: 14659507200 # parameter size
  release_date: "07/29/2025"

# Generator configuration
generator:
  temperature: 0.01
  top_p: 1.0
  max_tokens: 8192