wandb:
  run_name: "meta-llama/Llama-4-Scout-17B-16E-Instruct" # use run_name defined above

api: vllm-docker
num_gpus: 8
batch_size: 128 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "meta-llama/Llama-4-Scout-17B-16E-Instruct" #if you use openai api, put the name of model
  bfcl_model_id: "meta-llama/Llama-4-Scout-17B-16E-Instruct-FC"
  size_category: "Large (30B+)"
  size: 108641793536
  release_date: "4/5/2025"

vllm:
  vllm_tag: v0.10.1
  max_model_len: 131072 # OOM対策
  extra_args:
    - "--enable-expert-parallel"

