wandb:
  run_name: "llm-jp/llm-jp-3-3.7b-instruct" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨
# inference_interval: 1 # seconds

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "llm-jp/llm-jp-3-3.7b-instruct" #if you use openai api, put the name of model
  chat_template: "llm-jp/llm-jp-3-3.7b-instruct"
  size_category: "<10B"
  size: 3782913024
  release_date: "9/25/2024"
