wandb:
  run_name: mistral/mistral-large-2411
api: mistral
batch_size: 1
model:
  pretrained_model_name_or_path: mistral-large-2411
  bfcl_model_id: mistral-large-2411-FC
  base_model: null
  size_category: api
  size: null
  release_date: 11/24/2024 