wandb:
  run_name: "cyberagent/calm3-22b-chat-selfimprove-experimental" # use run_name defined above

api: vllm-docker
num_gpus: 1
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "cyberagent/calm3-22b-chat-selfimprove-experimental" #if you use openai api, put the name of model
  bfcl_model_id: "unified-oss-jsonschema"
  size_category: "Medium (10–30B)"
  size: 22542882816
  release_date: "2/13/2025"

vllm:
  vllm_tag: v0.10.1
