wandb:
  run_name: anthropic.claude-3-5-haiku-20241022-v1:0
api: amazon_bedrock
batch_size: 32
model:
  pretrained_model_name_or_path: us.anthropic.claude-3-5-haiku-20241022-v1:0
  bfcl_model_id: "claude-3-5-haiku-20241022-FC"
  base_model: "unknown"
  size_category: api
  size: null
  release_date: 10/22/2024

