wandb:
  run_name: google/gemini-2.5-flash-lite
api: google # openai, anthropic, google,..
batch_size: 32
model:
  pretrained_model_name_or_path: gemini-2.5-flash-lite #if you use openai api, put the name of model
  bfcl_model_id: "gemini-2.5-flash-lite-preview-06-17-FC" # find id from "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  base_model: "unknown"
  size_category: api
  size: null
  release_date: 6/17/2025
  thinking_budget: 0  # Flash-Lite models have thinking disabled (budget 0)
  safety_settings:
    - category: "HARM_CATEGORY_HATE_SPEECH"
      threshold: "BLOCK_NONE"
    - category: "HARM_CATEGORY_SEXUALLY_EXPLICIT"
      threshold: "BLOCK_NONE"
    - category: "HARM_CATEGORY_DANGEROUS_CONTENT"
      threshold: "BLOCK_NONE"
    - category: "HARM_CATEGORY_HARASSMENT"
      threshold: "BLOCK_NONE"
    - category: "HARM_CATEGORY_CIVIC_INTEGRITY"
      threshold: "BLOCK_NONE"
