wandb:
  run_name: stockmark/stockmark-13b-instruct
api: vllm
num_gpus: 2
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: stockmark/stockmark-13b-instruct #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: stockmark/stockmark-13b-instruct
  size_category: 10B≤ <30B
  release_date: 11/10/2023
