wandb:
  run_name: anthropic/claude-3.5-sonnet-20241022
api: openai-compatible # openai, anthropic, google,..
base_url: https://openrouter.ai/api/v1
batch_size: 32
model:
  pretrained_model_name_or_path: anthropic/claude-3.5-sonnet
  bfcl_model_id: OpenRouter-FC
  base_model: "unknown"
  size_category: api
  size: null
  release_date: 10/22/2024

generate:
  parallel_tool_calls: true