wandb:
  run_name: Qwen/Qwen2.5-32B-Instruct
api: vllm
num_gpus: 4
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: Qwen/Qwen2.5-32B-Instruct #if you use openai api, put the name of model
  bfcl_model_id: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: Qwen/Qwen2.5-32B-Instruct
  size_category: 30B≤
  size: 32763876352
  release_date: 9/19/2024
