wandb:
  run_name: "meta-llama/llama-3.3-70b-instruct"

api: "openai-compatible"
base_url: "https://openrouter.ai/api/v1"
batch_size: 32

model:
  pretrained_model_name_or_path: "meta-llama/llama-3.3-70b-instruct"  # APIで使用するモデル名
  bfcl_model_id: "meta-llama/Llama-3.3-70B-Instruct-FC" # find id from "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  size_category: "Large (30B+)"
  size: 70553706496
  release_date: "12/7/2024"

# Generator configuration
generator:
  max_tokens: 8192
  extra_body:
    provider:
      quantizations: ["bf16"]
      allow_fallbacks: false  # フォールバック無効