wandb:
  run_name: anthropic/claude-opus-4-1-20250805
api: openai-compatible # openai, anthropic, google,..
base_url: https://openrouter.ai/api/v1
batch_size: 32
model:
  pretrained_model_name_or_path: anthropic/claude-opus-4.1
  bfcl_model_id: OpenRouter-FC
  base_model: "unknown"
  size_category: api
  size: null
  release_date: 8/6/2025

generate:
  parallel_tool_calls: true