wandb:
  run_name: elyza/ELYZA-japanese-Llama-2-13b-instruct
api: vllm
num_gpus: 2
batch_size: 256
model:
  pretrained_model_name_or_path: elyza/ELYZA-japanese-Llama-2-13b-instruct #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: elyza/ELYZA-japanese-Llama-2-13b-instruct
  size_category: 10B≤ <30B
  size: 13144693760
  release_date: 12/27/2023
