wandb:
  run_name: augmxnt/shisa-gamma-7b-v1
api: vllm
num_gpus: 1
batch_size: 256
model:
  use_wandb_artifacts: false
  max_model_len: 3500
  pretrained_model_name_or_path: augmxnt/shisa-gamma-7b-v1 #if you use openai api, put the name of model
  bfcl_model_id: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: augmxnt/shisa-gamma-7b-v1
  size_category: <10B
  size: 7241732096
  release_date: 12/24/2023
