wandb:
  run_name: "tokyotech-llm/Llama-3.3-Swallow-70B-Instruct-v0.4" # use run_name defined above

api: vllm-docker
num_gpus: 8
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "tokyotech-llm/Llama-3.3-Swallow-70B-Instruct-v0.4" #if you use openai api, put the name of model
  bfcl_model_id: "unified-oss-jsonschema"
  size_category: "Large (30B+)"
  size: 70553706496
  release_date: "3/10/2025"

vllm:
  vllm_tag: v0.10.1
