wandb:
  run_name: anthropic/claude-opus-4-20250514-v1:0
api: amazon_bedrock
batch_size: 32
model:
  pretrained_model_name_or_path: us.anthropic.claude-opus-4-20250514-v1:0 #if you use openai api, put the name of model
  bfcl_model_id: "claude-opus-4-20250514-FC" # find id from "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  base_model: "unknown"
  size_category: api
  size: null
  release_date: 5/14/2025

